group:
  # SCDB
  - repos: |
      ssi-dk/SCDB

    files:
      - source: workflows/all-workflows.yaml
        dest: .github/workflows/all-workflows.yaml
        template:
          schemas: test,test.one
        config:
          tags: {
            variableStart: '<$',
            variableEnd: '$>'
          }

      - source: testthat/helper-setup.R
        dest: tests/testthat/helper-setup.R
        template:
          conn_list: >-
            "SQLite"              = "RSQLite::SQLite",
            "SQLite - w. schemas" = "RSQLite::SQLite"
          conn_args: >-
            "SQLite"              = list(dbname = file.path(tempdir(), "SQLite.SQLite")),
            "SQLite - w. schemas" = list(dbname = file.path(tempdir(), "SQLite_schemas.SQLite"))
          conn_post_connect: >-
            "SQLite - w. schemas" = list(
              paste0("ATTACH '", file.path(tempdir(), "SQLite_test.SQLite"), "' AS 'test'"),
              paste0("ATTACH '", file.path(tempdir(), "SQLite_test_one.SQLite"), "' AS 'test.one'")
            )
        config:
          autoescape: false


  # diseasyverse
  - repos: |
      ssi-dk/diseasystore
      ssi-dk/diseasy

    files:
      - source: workflows/all-workflows.yaml
        dest: .github/workflows/all-workflows.yaml
        template:
          schemas: test_ds,not_test_ds
        config:
          tags: {
            variableStart: '<$',
            variableEnd: '$>'
          }

      - source: testthat/helper-setup.R
        dest: tests/testthat/helper-setup.R
        template:
          conn_list: >-
            "SQLite" = "RSQLite::SQLite"
          conn_args: >-
            "SQLite" = list(dbname = file.path(tempdir(), "SQLite.SQLite"))
        config:
          autoescape: false
