group:
  # All repos
  - repos: |
      ssi-dk/SCDB
      ssi-dk/diseasystore
      ssi-dk/diseasy

    files:
    - source: templates/README_template.Rmd
      dest: .github/templates/README_template.Rmd

    - source: templates/PULL_REQUEST_TEMPLATE.md
      dest: .github/PULL_REQUEST_TEMPLATE.md

    - source: testthat/test-0_rd_files.R
      dest: tests/testthat/test-0_rd_files.R

    # Lintr related files
    - source: linting/.lintr
      dest: .lintr
    - source: linting/0_linters.R
      dest: R/0_linters.R
    - source: linting/test-0_linters.R
      dest: tests/testthat/test-0_linters.R

    # File syncing
    - source: .github/workflows/synchronise-files.yaml
      dest: .github/workflows/synchronise-files.yaml

    - source: .github/sync_reverse.yaml
      dest: .github/sync_reverse.yaml


  # SCDB
  - repos: |
      ssi-dk/SCDB

    files:
      - source: workflows/all-workflows.yaml
        dest: .github/workflows/all-workflows.yaml
        template:
          schemas: test,test.one
        config:
          tags: {
            variableStart: '<$',
            variableEnd: '$>'
          }

      - source: testthat/helper-setup.R
        dest: tests/testthat/helper-setup.R
        template:
          conn_list: |-
            "SQLite"              = "RSQLite::SQLite",
                  "SQLite - w. schemas" = "RSQLite::SQLite"
          conn_args: |-
            "SQLite"              = list(dbname = file.path(tempdir(), "SQLite.SQLite")),
                  "SQLite - w. schemas" = list(dbname = file.path(tempdir(), "SQLite_schemas.SQLite"))
          conn_post_connect: |-
            "SQLite - w. schemas" = list(
                    paste0("ATTACH '", file.path(tempdir(), "SQLite_test.SQLite"), "' AS 'test'"),
                    paste0("ATTACH '", file.path(tempdir(), "SQLite_test_one.SQLite"), "' AS 'test.one'")
                  )
        config:
          autoescape: false


  # diseasyverse
  - repos: |
      ssi-dk/diseasystore
      ssi-dk/diseasy

    files:
      - source: workflows/all-workflows.yaml
        dest: .github/workflows/all-workflows.yaml
        template:
          schemas: test_ds,not_test_ds
        config:
          tags: {
            variableStart: '<$',
            variableEnd: '$>'
          }

      - source: testthat/helper-setup.R
        dest: tests/testthat/helper-setup.R
        template:
          conn_list: |-
            "SQLite" = "RSQLite::SQLite"
          conn_args: |-
            "SQLite" = list(dbname = file.path(tempdir(), "SQLite.SQLite"))
        config:
          autoescape: false


ssi-dk/SCDB:
  - source: templates/_pkgdown.yml
    dest: _pkgdown.yml
    template:
      repo:
        name: SCDB

  - source: templates/bug_report.md
    dest: .github/ISSUE_TEMPLATE/bug_report.md
    template:
      repo:
        name: SCDB


ssi-dk/diseasy:
  - source: templates/_pkgdown.yml
    dest: _pkgdown.yml
    template:
      repo:
        name: diseasy

  - source: templates/bug_report.md
    dest: .github/ISSUE_TEMPLATE/bug_report.md
    template:
      repo:
        name: diseasy


ssi-dk/diseasystore:
  - source: templates/_pkgdown.yml
    dest: _pkgdown.yml
    template:
      repo:
        name: diseasystore

  - source: templates/bug_report.md
    dest: .github/ISSUE_TEMPLATE/bug_report.md
    template:
      repo:
        name: diseasystore
