```{r, Setup packages library}

# Lockfile should only be created when needed
## pak::lockfile_create("ssi-dk/diseasy", lib = "r-library", upgrade = TRUE)

# To run the script, please install the dependencies from the lockfile
# pak::lockfile_install(lib = "r-library")

# Determine the installed packages and R version
installation_state <- c(
  "R" = digest::digest(version),
  "packages" = digest::digest(readLines("pkg.lock"))
)

# Setup a cache for the analysis
cache <- cachem::cache_disk(dir = "cache/")
if (!identical(cache$get("installation_state"), installation_state)) {
  cache$reset()
  cache$set("installation_state", installation_state)
}
options("diseasy.cache" = cache)
  
# Set R to use the specific packages defined in the lockfile
.libPaths(file.path(getwd(), "r-library"))
stopifnot(endsWith(.libPaths()[1], "r-library"))
```

```{r, Load libraries}
library(diseasy)
```

#  First figure
For our first figure, we want to show the performance of the different methods in approximating some simple target curves
as the number of compartments increase.

For each of the three methods, we want to show their approximation for M = 1, 3, and 5 against a sigmoidal target
and a sum of exponentials.

```{r}
im <- DiseasyImmunity$new()

# Define custom waning functions
waning_functions <- list(
  "sigmoidal_waning" = \(t) exp(-(t - 1) * 6) / (1 + exp(-(t - 1) * 6)), 
  "sum_exp" = \(t) 1/3 * (exp(- t/2) + exp(-t) + exp(-2*t)),
  "exponential" = \(t) exp(-t)
)

# Get combinations of problems to solve
inputs <- tidyr::expand_grid(
  "target" = names(waning_functions),
  "method" = c("free_gamma", "free_delta", "all_free"),
  #"M" = c(1, 2, 3, 4)
  "M" = seq.int(from = 1, to = 10, by = 1)
) |>
  dplyr::left_join(
    tibble::enframe(waning_functions, name = "target", value = "waning_function"), 
    by = "target"
  )

# Generate approximations (stored in the cache)
approximation_output <- purrr::pmap(
  .progress = TRUE,
  inputs,
  \(target, method, M, waning_function, strategy) {
    im$set_custom_waning(
      custom_function = waning_function,
      target = "infection",
      name = target,
    )
    
    approx <- im$approximate_compartmental(method = method, M = M, strategy = "recursive")
    
    list(
      "gamma" = approx$gamma$infection,
      "delta" = approx$delta,
      "method"= method,
      "M" = M,
      "target" = target
    )
  }
)

# Get a reference to the internal helper functions
private <- im$.__enclos_env__$private


# Convert gamma and delta values to plotting functions
plotters <- purrr::map(
  approximation_output,
  ~ private$get_approximation(
    purrr::pluck(.x, "gamma"), 
    purrr::pluck(.x, "delta"),
    purrr::pluck(.x, "M")
  )
)

# Generate data.frame for plotting
generators <- cbind(inputs, tibble::tibble("approx_fun" = plotters))

t <- seq(0, 3, by = 1/ 10)
results <- generators |>
  tidyr::pivot_longer(c("waning_function", "approx_fun"), names_to = "type", values_to = "func") |>
  tidyr::crossing(t) |>
  dplyr::mutate(y = purrr::map2_dbl(.data$func, .data$t, \(f, t) f(t))) |>
  dplyr::select(!c("func"))

ggplot2::ggplot(results, ggplot2::aes(x = t, y = y, color = method)) +
  ggplot2::geom_line(ggplot2::aes(linetype = type)) + 
  ggplot2::facet_grid(M ~ target)
```

```{r}
residuals <- dplyr::left_join(
  results,
  results |>
    dplyr::filter(.data$type == "waning_function", .data$method == "all_free", .data$M == 1) |>
    dplyr::transmute(.data$target, .data$t, "y_ref" = .data$y),
  by = c("t", "target")
) |>
  dplyr::mutate(
    "residual" = .data$y - .data$y_ref,
    "method" = dplyr::if_else(.data$type == "waning_function", NA, .data$method)
  ) |>
  tidyr::pivot_longer(c("y", "residual")) |>
  dplyr::distinct()
    
```

```{r}
residuals |>
  dplyr::filter(.data$target == "sum_exp", .data$M %in% c(2, 4, 6)) |>
  dplyr::mutate("name" = factor(.data$name, levels = c("y", "residual"))) |>
  ggplot2::ggplot(ggplot2::aes(x = t, y = value, color = method)) +
  ggplot2::geom_line(ggplot2::aes(linetype = type), linewidth = 1) +
  ggplot2::facet_grid(M ~ name)
  
```

```{r}
residuals |>
  dplyr::filter(.data$target == "sigmoidal_waning", .data$M %in% c(2, 4, 6, 8, 10)) |>
  dplyr::mutate("name" = factor(.data$name, levels = c("y", "residual"))) |>
  ggplot2::ggplot(ggplot2::aes(x = t, y = value, color = method)) +
  ggplot2::geom_line(ggplot2::aes(linetype = type), linewidth = 1) +
  ggplot2::facet_grid(M ~ name)
  
```



```{r}
im$set_custom_waning(custom_function = waning_functions[["sum_exp"]])
im$plot(method = "free_delta", M = 4, strategy = "naive")
im$plot(method = "all_free", M = 4, strategy = "naive")
im$plot(method = "all_free", M = 4, strategy = "recursive")
```

```{r}
im <- DiseasyImmunity$new()
im$set_exponential_waning()
#im$set_custom_waning(custom_function = waning_functions[["sum_exp"]])
im$plot(M = 3, method = "free_gamma", strategy = "recursive")
```

