# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branch: [main, master]
    paths:
      - R/**
      - tests/**
  pull_request:
    branch: [main, master]
    paths:
      - R/**
      - tests/**

name: Check code coverage

jobs:
  code-coverage:
    steps:
      - uses: actions/checkout@v4

      - uses: ssi-dk/AEF-DDF/.github/workflows/code-coverage.yaml@main
        with:
          schema_creation: '"CREATE SCHEMA test; CREATE SCHEMA \"test.one\";"'
          repository: ${{ github.repository }}