# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branch: [main, master]
    paths:
      - R/**
      - man/**
  pull_request:
    branch: [main, master]
    paths:
      - R/**
      - man/**

name: lint

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
