# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - R/**
      - tests/**
      - man/**
      - vignettes/**
  pull_request:
    branches: [main, master]
        paths:
      - R/**
      - tests/**
      - man/**
      - vignettes/**

name: Run R-CMD-check

jobs:
  R-CMD-check:
    uses: ssi-dk/AEF-DDF/.github/workflows/R-CMD-check.yaml@main
    secrets: inherit
