# Workflow frrom https://github.com/marketplace/actions/r-dependency-license-report

---
name: License Report

on:
  push:
    branches-ignore: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  license-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: License Report
        uses: insightsengineering/r-license-report@v1