on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        required: true
      cache_version:
        type: string
        default: '1'
      document:
        type: boolean
        default: true
      render_readme:
        type: boolean
        default: true
      styler:
        type: boolean
        default: false


jobs:
  document-render-readme-styler:
    name: 📖 Document, Update README, and enforce coding style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git switch "${{ inputs.branch_name }}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ inputs.cache_version }}
          extra-packages: |
            local::.
            any::pak
            any::jsonlite
            any::rcmdcheck
            any::devtools
            any::lintr
            any::covr
            any::roxygen2
            any::pkgdown
            any::rmarkdown
            any::styler
          needs: build, check, coverage, roxygen2, lint, website

      - name: 📝 Enforce code style
        if: ${{ inputs.styler == true }}
        run: |
          # Set custom style
          diseasy_style <- function(...) {
            transformers <- styler::tidyverse_style(...)
            transformers$space$spacing_before_comments <- NULL
            transformers
          }

          styler::style_pkg(style = diseasy_style)
        shell: Rscript {0}

      - name: Commit and push changes
        if: ${{ inputs.styler == true }}
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY.git
          git stash
          git pull --rebase origin ${{ inputs.branch_name }}
          git stash list | grep stash@{0} && git stash pop || echo "No stash to pop"
          git add *.R && git add *.Rmd
          git commit -m "chore: Enforce code style" || echo "No changes to commit"
          git push origin ${{ inputs.branch_name }}

      - name: 📖 Document
        if: ${{ inputs.document == true }}
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and push changes
        if: ${{ inputs.document == true }}
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY.git
          git stash
          git pull --rebase origin ${{ inputs.branch_name }}
          git stash list | grep stash@{0} && git stash pop || echo "No stash to pop"
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "docs: Re-build roxygen documentation" || echo "No changes to commit"
          git push origin ${{ inputs.branch_name }}

      - name: 📖 Render README
        if: ${{ inputs.render_readme == true }}
        run: rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      - name: Commit and push changes
        if: ${{ inputs.render_readme == true }}
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY.git
          git stash
          git pull --rebase origin ${{ inputs.branch_name }}
          git stash list | grep stash@{0} && git stash pop || echo "No stash to pop"
          git add README.md
          git commit -m "docs(README): Re-build README.Rmd" || echo "No changes to commit"
          git push origin ${{ inputs.branch_name }}
