on:
  workflow_call:
    inputs:
      run:
        type: boolean
        default: true

jobs:
  render:
    if: ${{ inputs.run }}
    name: 📖 Render README
    runs-on: ubuntu-latest
    steps:
      - name: Report skipping
        run: echo "${{ inputs.run }}"
      - name: Test skipping
        if: ${{ inputs.run }}
        run: echo "Skipping works!"
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'docs: Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
