on:
  workflow_call:
    inputs:
      run:
        type: boolean
        default: true
      branch_name:
        type: string
        required: true

jobs:
  render:
    if: ${{ inputs.run }}
    name: 📖 README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'docs(README): Re-build README.Rmd' || echo "No changes to commit"
          git push origin HEAD:${{ inputs.branch_name }}
