on:
  workflow_call:
    inputs:
      run:
        type: boolean
        default: true
      branch_name:
        type: string
        required: true

jobs:
  render:
    if: ${{ inputs.run }}
    name: 📖 README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git switch ${{ inputs.branch_name }}

      - name: Setup Node.Js
        uses: actions/setup-node@v4

      - name: Install nunjucks
        run: npm install nunjucks

      - name: Resolve nunjucks templates
        run: |
          echo "
            const nunjucks = require('nunjucks');
            const fs = require('node:fs');

            nunjucks.configure({ autoescape: true, trimBlocks: true, lstripBlocks: true });

            var res = nunjucks.render('README.Rmd', {repo_name: '${{ github.event.repository.name }}'});

            fs.writeFile('README.Rmd', res, (err) => err && console.error(err));" >> render-templates.js
          node render-templates.js

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit and push changes
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY.git
          git pull --rebase origin ${{ inputs.branch_name }}
          git commit README.md -m 'docs(README): Re-build README.Rmd' || echo "No changes to commit"
          git push origin ${{ inputs.branch_name }}
