on:
  workflow_call:
    inputs:
      cache_version:
        type: string
        default: '1'
      run:
        type: boolean
        default: true
      branch_name:
        type: string
        required: true

jobs:
  update-lockfile:
    name: 🛠️ Store dependency versions
    if: ${{ inputs.run }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ inputs.cache_version }}
          extra-packages: any::pak

      - name: Update the pak.lock file
        run: pak::lockfile_create(".", lockfile = "pak.lock", dependencies = TRUE)
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git switch ${{ inputs.branch_name }}
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "chore: update pak.lock" || echo "No changes to commit"
          git push
