on:
  workflow_call:
    inputs:
      cache_version:
        type: string
        default: '1'
      run:
        type: boolean
        default: true
      branch_name:
        type: string
        required: true

jobs:
  lint:
    name: 🛠️ Store dependency versions
    if: ${{ inputs.run }}
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ inputs.cache_version }}
          extra-packages: any::renv

      - name: Update the renv.lock file
        run: renv::snapshot(prompt = FALSE)
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git switch ${{ inputs.branch_name }}
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "chore: update renv.lock" || echo "No changes to commit"
          git push
