on:
  workflow_call:
    inputs:
      cache_version:
        type: string
        default: '1'
      branch_name:
        type: string
        required: true

jobs:
  update-lockfile:
    name: 🛠️ Store dependency versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git switch ${{ inputs.branch_name }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ inputs.cache_version }}
          extra-packages: any::pak, any::jsonlite

      - name: Update the pak.lock file
        run: |
          pak::lockfile_create(".", lockfile = "pak.lock", dependencies = TRUE)
          lockfile <- jsonlite::fromJSON("pak.lock")
          lockfile$packages <- dplyr::arrange(lockfile$packages, "ref")
          jsonlite::write_json(lockfile, "pak.lock", pretty = TRUE, auto_unbox = TRUE)
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/$GITHUB_REPOSITORY.git
          git stash --include-untracked
          git pull --rebase origin ${{ inputs.branch_name }}
          git stash list | grep stash@{0} && git stash pop || echo "No stash to pop"
          git add pak.lock || echo "No pak.lock to add"
          if git commit -m "chore: Update pak.lock"; then
            git push origin ${{ inputs.branch_name }}
            echo "Changes committed. Failing the job to prevent further jobs."
            exit 1
          else
            echo "No changes to commit"
          fi
